title: "Damour Nsanzimfura AI Inc"
author: "Nsarob"
description: "Vladimir State University"
lang: "en"
permalink: /:title/
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Theme Settings
remote_theme: cotes2020/jekyll-theme-chirpy
theme: null

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives

# UI Settings
toc: true
paginate: 5
paginate_path: "/page:num/"

# Collections
collections:
  lab:
    output: true
  projects:
    output: true

# Navigation (Chirpy tabs use _tabs directory)
# We'll manage menu via tab files

# Footer Social Links
social:
  email: roboticsdamour447@gmail.com
  github: Nsarob
  linkedin: damour-nsanzimfura

# Comments (optional)
#disqus:
#  shortname: your-disqus-shortname

# Optional External Tools
# google_analytics: UA-XXXXXXXX-X
